name: dockerize-react-app

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: react-docker-image
    container_name: react-container
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
